language: go

go:
  - 1.7

env:
  global:
  - SSH_KEY="travis-key"
  - ENCRYPTION_LABEL="0fe0dae8358a"
  - GIT_NAME="Peter Y. Chuang"
  - GIT_EMAIL="peteryuchuang@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"

branches:
  only:
  - source

cache:
  directories:
  - "$HOME/gopath/bin/"
install:
  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
  - tar -xvzf hugo_0.18.1_Linux-64bit.tar.gz
  - cd hugo_0.18.1_linux_amd64
  - mv hugo_0.18.1_linux_amd64 hugo
  - mv hugo $HOME/gopath/bin/
  - cd ..

before_install:
- openssl aes-256-cbc -K $encrypted_0fe0dae8358a_key -iv $encrypted_0fe0dae8358a_iv
  -in travis-key.enc -out travis-key -d
before_script:
- pip install --user pygments
- npm install -g gulp-cli
- npm install gulp
- npm install gulp-htmlmin
- npm install gulp-base64

script:
- hugo
- gulp deploy
- echo extrafinewriter.com > ./public/CNAME
- touch ./public/.nojekyll
- sh ./deploy.sh

notifications:
  slack:
    secure: flHMkCq6/MQMInsXnjsLEnGCRNHNfldPnVwBNcQE68dzD1cgdOGCFQfsSgfa0fk3GozP2y0zdbDvKUsKhkswynpBErDuozjs/nOFRzzikF0Feyh40edfbeuR+teKRT6+dWNRm0fT8EVUE/x/N+20S7I0WjjleN6rhFsxtF3V3AXZ73CqUXfgpyxZyhwJhxCXne1r5G6hdjDN+excHzMfgafBJnYCA/II1n/Uus0TjqxATM4z8yzh596YJLAtP8tRGd+dl8pmfHR9Qag4e998rgau6HHf/f2IihrrL8U7/KGMr0HMlksKzc+ZBZoJUMQE3L5YGEfiSdt90Bker8ZX0Od7aIc5EID1NsIX/oBj038E5w53pDQzv0Ht8yR20TRMr8AK7eBvFZhutGgcIRr/2sZyYaJlI+0PAPSxZo5TaR23r5j5t+heiFvFF2JzWX2bGBISGN42iY31WNjZBQzDlEjCk/0/q+ehSjtkruf7aHf3xZIfUpEpVjhwK/c6fymvf5zO1OBlKbjgeVv6eAS/nxqTFqhE1hpU7UAzmTNFYZgLubn6jY8e7KxSF2g/4yMZEzGnFqGyDp45eH9CzJA9qNleHFTADLHAsGjIkhqghehDfp7BXuY7wvg/jgkCabvFzKnXWtfjO/6tcbb8zcWgTpLAGIH/2TbhojHIfQTwcGg=
  on_success: always
  on_failure: always
